load_data:
  dataset_csv: "artifacts/downloaded_dataset.csv"

# Train - data to train the model
# Test - data to train the model
# Val - data to validate that the training is working
split_data:
  train_proportion: 0.7
  val_proportion_wrt_test: 0.5
  random_state: 12
  train_dataset_path: "artifacts/split_train_dataset.csv"
  test_dataset_path: "artifacts/split_test_dataset.csv"
  val_dataset_path: "artifacts/split_val_dataset.csv"

features:
  features_train_dataset: "artifacts/features_train_dataset.csv"
  features_test_dataset: "artifacts/features_test_dataset.csv"
  features_val_dataset: "artifacts/features_val_dataset.csv"

train:
  model_name: "StudentGradePrediction KNN"
  algo: "knn"
  n_neighbors: 11
  algorithm: "auto"
  metric: "manhattan"
  weights: "distance"
  # Save the trained model here
  model_path: "artifacts/model_test1.pkl"
